name: "Trigger PR Workflow"
description: "Triggers PR workflows externally from the PR events"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "index.cjs"
