name: "Trigger PR Workflow"
description: "Triggers PR workflows externally from the PR events"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
  state:
    description: "What state should the PR be in open/closed"
    required: false
    default: "all"
  label:
    description: "Label the PR should contain"
    required: false
    default: ""
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "index.js"
